version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
  auth:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      CORAL_AUTH_PORT: 5000
      CORAL_AUTH_MONGO_URL: "mongodb://mongo/test"
    env_file: .env
    depends_on:
      - mongo
volumes:
  mongo:
    external: false
